### ISSUE TITLE
Apply Dipper for new dataset

### ISSUE THREAD

**Issue by kirudang** [martiansideofthemoon/ai-detection-paraphrases#12]
Hello,

I wonder if we could use Dipper to paraphrase texts from C4 dataset?
I know that we need to train Dipper first but the problem is I dont have parallel dataset for C4 texts.
Do you have any suggestion.

Thank you.

**Comment by martiansideofthemoon** [comment]
Yes it should work decently well (based on some experiments we did that didn't make it to the paper).
