### ISSUE TITLE
How to fix thresholds

### ISSUE THREAD

**Issue by ryuryukke** [martiansideofthemoon/ai-detection-paraphrases#5]
Hi, thank you for sharing the code.
I found fixed thresholds for each detection algorithm.
Are these thresholds fixed to satisfy that FPR is precisely 1%?
If so, how do you get these?

Thanks

**Comment by martiansideofthemoon** [comment]
Hi @ryuryukke,
Thanks for your interest in our work. We actually adaptively adjust the threshold to get to match 1% FPR on the particular setting. We use this function to do that:

https://github.com/martiansideofthemoon/ai-detection-paraphrases/blob/main/dipper_paraphrases/utils.py#L106

**Comment by martiansideofthemoon** [comment]
Closing this for now, please re-open if the issue is not yet resolved..
