### ISSUE TITLE
Wrong argument name in detect_watermark.py

### ISSUE THREAD

**Issue by dkoterwa** [martiansideofthemoon/ai-detection-paraphrases#8]
Hi,
I am trying to replicate your experiments and detect_watermark.py raises an error "AttributeError: 'Namespace' object has no attribute 'watermark_cache'". I think that **watermark_cache** argument **should be replaced with detector_cache** in chunk of code posted below. 

```
if cache1 or cache2 or cache3:
        # save cache
        with open(args.watermark_cache, "w") as f:
            json.dump(cache, f)
```

**Maybe it is just enough to replace the name of the argument in the script call in README.**

**Comment by martiansideofthemoon** [comment]
Hi @dkoterwa, yes that's true. Please feel free to send a PR to fix this

**Comment by martiansideofthemoon** [comment]
Thank you for your contribution!!
