### ISSUE TITLE
Wrong saving parameters in dipper_paraphrases/detect_retrieval.py

### ISSUE THREAD

**Issue by mizuki-p** [martiansideofthemoon/ai-detection-paraphrases#9]
Hello,
I found detect_retrieval.py saves two identical tuples in the result file, and I think the script initially attempted to save both the paraphrased and the generation results.

relative code (dipper_paraphrases/detect_retrieval.py line 141):
``` python
plot1 = get_roc(human_detect, paraphrase_detect)
print_tpr_target(plot1[0], plot1[1], "paraphrase", args.target_fpr)
plot2 = get_roc(human_detect, generation_detect)
print_tpr_target(plot2[0], plot2[1], "generation", args.target_fpr)

with open("roc_plots/s2_sim.pkl", 'wb') as f:
    pickle.dump((plot1, plot1), f)
```

change
```  python
pickle.dump((plot1, plot1), f)
```
to
``` python
pickle.dump((plot1, plot2), f)
```
may fix it

**Comment by martiansideofthemoon** [comment]
Hi @mizuki-p, thanks for your interest and reporting this issue. While this issue will not affect any workflows on the public Github, please feel free to send a PR fixing it. Thank you!

**Comment by martiansideofthemoon** [comment]
Thank you for your contribution!
